# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starup', models.CharField(default='', max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(default='', max_length=25)),
                ('descripcion', models.TextField(default='', max_length=140)),
                ('imagenes', models.ImageField(upload_to='media/')),
                ('video', models.URLField()),
                ('invitadoMail', models.EmailField(max_length=50)),
            ],
        ),
    ]
